#%RAML 1.0
title: Customer
baseUri: http://localhost:8081/{version}
version: v1
description: Customer Inquiry Service

/customer:
  get:
    responses:
      200:
        body:
          application/json:
            properties:
              records:
                type: array
                items: !include customer_object.raml

              